language: python

dist: focal

matrix:
  include:
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.9"
      env: TOXENV=py39
    - python: "3.10"
      env: TOXENV=py310

install:
  - pip install .
  - pip install codecov
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt


# run tests
script:
  - tox

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
